import os
import lit.formats

config.name = "umbral"
config.test_format = lit.formats.ShTest()
config.suffixes = [".um"]
config.test_source_root = os.path.dirname(__file__)

# These are populated by lit.site.cfg.py (generated by CMake)
config.substitutions.append(("%uc", config.uc_path))
config.substitutions.append(("%ul", config.ul_path))
config.substitutions.append(("%FileCheck", config.filecheck_path))
