#define UMBRAL_INTRINSICS(X) \
  X(As,        "as")         \
  X(Bitcast,   "bitcast")    \
  X(SiteId,    "site_id")    \
  X(SizeOf,    "size_of")    \
  X(AlignOf,   "align_of")   \
  X(SliceCast, "slice_cast") \
  X(Iter,      "iter")       \
  X(MemCpy,    "memcpy")     \
  X(MemMov,    "memmov")     \
  X(MemSet,    "memset")     \
  X(MemCmp,    "memcmp")     \
  X(MetaGen,    "gen")       \
  X(MetaElseIf, "else_if")   \
  X(MetaFields, "fields")    \
  X(MetaField,  "field")     \
  X(MetaAssert, "assert")
