#define UMBRAL_KEYWORDS(X)                                                         \
  X(Fn, "fn")                                                                  \
  X(Let, "let")                                                                \
  X(Mut, "mut")                                                                \
  X(If, "if")                                                                  \
  X(Else, "else")                                                              \
  X(For, "for")                                                                \
  X(Return, "return")                                                          \
  X(Struct, "struct")                                                           \
  X(Type, "type")                                                              \
  X(Impl, "impl")                                                              \
  X(Module, "module")                                                          \
  X(Import, "import")                                                          \
  X(Pub, "pub")                                                                \
  X(True_, "true")                                                             \
  X(False_, "false")                                                          \
  X(Var, "var")                                                               \
  X(As, "as")
